spring:
    main:
        web-application-type: reactive
        # allow-bean-definition-overriding: true
        # spring.main.allow-bean-definition-overriding=true
    cloud:
        # discovery:
        # enabled: false  
        # spring.cloud.discovery.client.health-indicator.enabled=false
        # spring.cloud.kubernetes.loadbalancer.mode=SERVICE
        discovery:
            client:
                health-indicator:
                    enabled: false    
                composite-indicator:
                    enabled: false 
        gateway :
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:        
                  - id: auth-route
                    uri: lb://authservice
                    predicates:
                        - Path=/auth/**
                    filters:
                        - name: Retry
                          args: 
                            retries: 3
                            method: GET
                            backoff:
                                firstBackOff: 50ms
                                maxBackOff: 500ms
                        - name: CircuitBreaker
                          args:
                            name: authservice
                            fallbackUri: forward://auth-fallback
                  - id: product-route
                    uri: lb://productservice
                    predicates :
                        - Path=/products/**
                    filters:
                        - name: AuthenticationFilter
                        - name: Retry
                          args:
                            retries: 3
                            methods: GET
                            backoff:
                                firstBackOff: 50ms
                                maxBackOff: 500ms
                        - name: CircuitBreaker
                          args:
                            name: productservice
                            fallbackUri: forward:/product-fallback                  
        kubernetes:
            discovery:
                enabled: true 
                all-namespaces: false
                include-not-ready-addresses: true
                discovery-server-url: "http://spring-cloud-kubernetes-discoveryserver:8761"
            loadbalancer:
                mode: SERVICE
# ingress controller service url - minikube service list
#ignore null fields in json
    jackson :
        default-property-inclusion: NON_NULL
#secret key - should be encrypted
jwt:
    secret: secretkey
    token:
        validity: 180000

logging:
    file: 
        name: app-gateway.log
    level:
        root: info
    com.supershopee.gateway: info
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss,SSS} %5p [%t] %c [%M] - %m%n"
