management:
 health:
   circuitbreakers:
      enabled: true
 endpoint:
   health:
      show-details: always
 endpoints:
   web:
      exposure:
         include: "*"
spring:
  main:
     web-application-type: reactive
  cloud :
    gateway :
       discovery:
           locator:
              enabled: true
              lower-case-service-id: true
       routes :
          - id : drug-service-route
            uri : http://localhost:8090
            predicates :
              - Path=/drug-details/**
            filters:
              - name: Retry
                args :
                  name : drug-details
                  max-attempts: 3
                  wait-duration: 5s
                  enable-exponential-backoff: true
                  exponential-backoff-multiplier: 2
                  retry-exceptions:
                    - java.util.concurrent.TimeoutException
                  ignore-exceptions:
                    - com.supershopee.gateway.exception.IgnoreException
              - name : CircuitBreaker
                args :
                  name : drug-details
                  fallbackUri : forward:/drugs-fallback
resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 5s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
         - java.util.concurrent.TimeoutException
        ignore-exceptions:
         - com.supershopee.gateway.exception.IgnoreException
    retry-aspect-order: 2
    instances:
        drug-details:
           baseConfig: default 
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 2s
        failureRateThreshold: 5
        eventConsumerBufferSize: 10
        slowCallDurationThreshold: 200ms
        slowCallRateThreshold: 30
        #recordExceptions:
          #- org.springframework.web.client.HttpServerErrorException
          #- java.io.IOException
        #ignoreExceptions:
          #- java.lang.IllegalStateException
    circuit-breaker-aspect-order: 1
    instances:
        drug-details:
            baseConfig: default               
               
#secret key - should be encrypted
jwt:
  secret: secretkey
  token:
    validity: 180000

logging:
  file: 
    name: app-gateway.log
  level:
     root: info
     org.springframework : debug
     com.supershopee.gateway: info
  pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} %5p [%t] %c [%M] - %m%n"
