spring:
   datasource:
      #username: ${mysqldbusername}
      #password: ${mysqldbpassword}
      username: root
      password: ravi@mysql70
      url: jdbc:mysql://localhost:3307/supershopee?useSSL=false&allowPublicKeyRetrieval=true
   jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      hibernate:
         ddl-auto : update
      properties :
         hibernate:
             format-sql : true
